### ISSUE TITLE
Cannot run styx daemon

### ISSUE THREAD

**Issue by ElXreno** [dnr/styx#1]
I installed styx as described in the readme (first install). However, the service itself won't start, claiming an invalid argument.

```bash
Nov 24 04:24:12 INFINITY systemd[1]: Starting Nix storage manager...
Nov 24 04:24:12 INFINITY styx[218191]: daemon.go:243: initializing with empty config, call 'styx init --params=...'
Nov 24 04:24:12 INFINITY styx[218191]: Error: invalid argument
Nov 24 04:24:12 INFINITY styx[218191]: Usage:
Nov 24 04:24:12 INFINITY styx[218191]:   styx daemon [flags]
Nov 24 04:24:12 INFINITY styx[218191]: Flags:
Nov 24 04:24:12 INFINITY styx[218191]:       --block_shift int      block size bits for local fs images (default 12)
Nov 24 04:24:12 INFINITY styx[218191]:       --cache string         path to local cache (also socket and db) (default "/var/cache/styx")
Nov 24 04:24:12 INFINITY styx[218191]:       --cachedomain string   cachefiles domain (default "styx")
Nov 24 04:24:12 INFINITY styx[218191]:       --cachetag string      cachefiles tag (default "styx0")
Nov 24 04:24:12 INFINITY styx[218191]:       --devpath string       path to cachefiles device node (default "/dev/cachefiles")
Nov 24 04:24:12 INFINITY styx[218191]:   -h, --help                 help for daemon
Nov 24 04:24:12 INFINITY styx[218191]:       --workers int          worker goroutines for cachefilesd serving (default 16)
Nov 24 04:24:12 INFINITY styx[218191]: main.go:407: invalid argument
Nov 24 04:24:12 INFINITY systemd[1]: styx.service: Main process exited, code=exited, status=1/FAILURE
```

Reproduces on: https://github.com/dnr/styx/commit/499d6f76c4d5308013e55d6529ec08540020e6de

**Comment by dnr** [comment]
Thanks for the report, you're probably the first person to actually try it out.

The logging should definitely be improved to report where that error is from, but a few guesses:
- What kernel version are you running (`uname -a`) and does it include the config in the module (`CACHEFILES_ONDEMAND` and `EROFS_FS_ONDEMAND`)?
- Is there any other non-standard kernel stuff in your system config?
- Did it manage to create `/var/cache/styx` or did it fail before that?
- Did it manage to create `/dev/cachefiles` or fail before that?
- What filesystem are you using for your root filesystem?

**Comment by ElXreno** [comment]
I think I've found the cause. I simply forgot to reboot with the new kernel. After reboot the `styx.service` started successfully. I'm sorry about that.
Maybe we should add a check to see if `CACHEFILES_ONDEMAND` and `EROFS_FS_ONDEMAND` are present in the current kernel config (I mean something like `zcat /proc/config.gz | grep -E "CACHEFILES_ONDEMAND|EROFS_FS_ONDEMAND"`) before starting up in daemon mode?


> What kernel version are you running (`uname -a`) 
```
Linux INFINITY 6.12.0 #1-NixOS SMP PREEMPT_DYNAMIC Sun Nov 17 22:15:08 UTC 2024 x86_64 GNU/Linux
```
> Is there any other non-standard kernel stuff in your system config?

I'm using the default kernel provided by nixpkgs with no modifications.

> Did it manage to create `/var/cache/styx` or did it fail before that?

Yes, it successfully created this directory.

> Did it manage to create `/dev/cachefiles` or fail before that?

No, there's no `/dev/cachefiles`.

> What filesystem are you using for your root filesystem?

BTRFS.

**Comment by dnr** [comment]
Ah, I thought that might be it.

If those config options are missing, then it'll fail on this specific line: https://github.com/dnr/styx/blob/499d6f76c4d5308013e55d6529ec08540020e6de/daemon/daemon.go#L331
so I think I can just add more error wrapping there to make it clearer.

**Comment by dnr** [comment]
I added more logging in df44d58 and also changed how it loads the module, so hopefully this sort of thing will be easier to diagnose next time.
